# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Matthew leert Nederlands
email: matthewyeah@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 A simple blog to practice writing in Dutch. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
twitter_username: matthewhicks_
github_username:  matthewyeah

# Build settings
markdown: kramdown

future: true

# assets:
#   assets_dir: _assets
# include: ['_assets']

# gems:
#   - jekyll-assets

# assets:
#   sources:
#     - _assets
#     - _assets/fonts
#     - _assets/images
